import {pageMarkup,esc,cropRect} from '/layout.js';
const $=s=>document.querySelector(s);let book={pages:[],assets:[]},selected=-1,revision=0,savedRevision=0,timer,saving=Promise.resolve(),renderVersion=0,toastTimer;
const previews=new Map(),images=new Map();
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500)}
async function api(url,options={}){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(data.error||'操作失败');return data}
const page=()=>book.pages[selected];
function mark(){revision++;$('#save-state').textContent='正在保存…';clearTimeout(timer);timer=setTimeout(save,500)}
function save(){clearTimeout(timer);const rev=revision;const snapshot=JSON.stringify(book);saving=saving.catch(()=>{}).then(async()=>{try{await api('/api/draft',{method:'PUT',headers:{'Content-Type':'application/json'},body:snapshot});savedRevision=rev;if(rev===revision)$('#save-state').textContent='草稿已保存'}catch(e){$('#save-state').textContent='保存失败 · 点击重试';toast(e.message);throw e}});saving.catch(()=>{});return saving}
$('#save-state').onclick=()=>save();
function loadImage(asset){if(!images.has(asset.id))images.set(asset.id,new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>{images.delete(asset.id);reject(Error('照片无法读取，请确认图像文件完整'))};img.src=asset.url}));return images.get(asset.id)}
async function renderPhoto(p,max=1200){const asset=book.assets.find(a=>a.id===p.assetId);if(!asset)throw Error('找不到照片原图');const img=await loadImage(asset),crop=cropRect(img.naturalWidth,img.naturalHeight,p.ratio,p.zoom,p.x,p.y);const scale=Math.min(1,max/Math.max(crop.sw,crop.sh));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(crop.sw*scale));canvas.height=Math.max(1,Math.round(crop.sh*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,crop.sx,crop.sy,crop.sw,crop.sh,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',max>1200?.94:.85)}
function drawAssets(){$('#asset-count').textContent=String(book.assets.length).padStart(2,'0');$('#assets').innerHTML=book.assets.map(a=>`<button data-asset="${esc(a.id)}" title="${esc(a.name)} · 点击添加"><img src="${esc(a.url)}" alt="${esc(a.name)}" loading="lazy"></button>`).join('');$('#drop-hint').hidden=book.assets.length>0}
function drawThumbs(){$('#total-pages').textContent=String(book.pages.length).padStart(2,'0');$('#thumbnails').innerHTML=book.pages.map((p,i)=>`<div role="button" tabindex="0" class="thumb ${i===selected?'active':''}" data-index="${i}" aria-label="第 ${i+1} 页 ${esc(p.title||'未命名')}" aria-pressed="${i===selected}"><span class="thumb-number">${String(i+1).padStart(2,'0')}</span><div class="thumb-sheet" inert>${pageMarkup(p,i,previews.get(p.id)||book.assets.find(a=>a.id===p.assetId)?.url)}</div></div>`).join('')}
async function drawCanvas(){const version=++renderVersion,p=page();$('#empty-canvas').hidden=!!p;$('#page-canvas').innerHTML=p?pageMarkup(p,selected,previews.get(p.id)||book.assets.find(a=>a.id===p.assetId)?.url):'';$('#selection-label').textContent=p?`第 ${String(selected+1).padStart(2,'0')} 页 · 单页排版`:'单页排版';$('#page-position').textContent=p?`${selected+1} / ${book.pages.length}`:'';
 if(p?.type==='photo')try{const src=await renderPhoto(p);if(version!==renderVersion)return;previews.set(p.id,src);const img=$('#page-canvas img');if(img)img.src=src;drawThumbs()}catch(e){toast(e.message)}
}
function drawInspector(){const p=page();$('#inspector-empty').hidden=!!p;$('#inspector-fields').hidden=!p;$('#page-kind').textContent=p?({photo:'摄影作品',text:'白页',chapter:'章节'}[p.type]):'—';if(!p)return;const photo=p.type==='photo';$('#photo-fields').hidden=!photo;$('#text-fields').hidden=photo;$('#image-controls').hidden=!photo;document.querySelectorAll('[data-field]').forEach(el=>el.value=p[el.dataset.field]||'');document.querySelectorAll('[data-size]').forEach(el=>el.classList.toggle('active',el.dataset.size===p.size));$('#crop-ratio').value=p.cropRatio||'original';$('#crop-zoom').value=p.zoom||1;$('#crop-value').textContent=(p.zoom||1).toFixed(2)+'×';$('#crop-x').value=p.x??.5;$('#crop-y').value=p.y??.5;$('#move-up').disabled=selected===0;$('#move-down').disabled=selected===book.pages.length-1}
function select(index){selected=index;drawThumbs();drawCanvas();drawInspector()}
function add(p){book.pages.splice(selected+1,0,p);selected++;mark();select(selected)}
async function addAsset(id){const a=book.assets.find(a=>a.id===id);try{const img=await loadImage(a);add({id:crypto.randomUUID(),type:'photo',assetId:id,title:'',location:'',date:'',film:'',format:'',description:'',size:'large',ratio:img.naturalWidth/img.naturalHeight,originalRatio:img.naturalWidth/img.naturalHeight,cropRatio:'original',zoom:1,x:.5,y:.5})}catch(e){toast(e.message)}}
$('#assets').onclick=e=>{const b=e.target.closest('[data-asset]');if(b)addAsset(b.dataset.asset)};$('#thumbnails').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const b=e.target.closest('[data-index]');if(b){e.preventDefault();select(+b.dataset.index)}}};$('#thumbnails').onclick=e=>{const b=e.target.closest('[data-index]');if(b)select(+b.dataset.index)};
$('#add-chapter').onclick=()=>add({id:crypto.randomUUID(),type:'chapter',title:'新的章节',text:'',chapter:book.pages.filter(p=>p.type==='chapter').length+1,template:'center'});$('#add-text').onclick=()=>add({id:crypto.randomUUID(),type:'text',title:'',text:'',template:'center'});
let importing=false;async function upload(files){if(importing)return;importing=true;$('#upload').disabled=true;try{await save();for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast(`${file.name}：请转换为 JPEG、PNG 或 WebP`);continue}if(file.size>100*1024*1024){toast(`${file.name} 超过 100 MB`);continue}$('#save-state').textContent=`正在导入 ${file.name}`;const asset=await api('/api/assets',{method:'POST',headers:{'Content-Type':file.type,'X-Filename':encodeURIComponent(file.name)},body:file});book.assets.push(asset);drawAssets()}$('#save-state').textContent='素材已保存';toast('导入完成，点击素材即可加入页面。')}catch(e){toast(e.message)}finally{importing=false;$('#upload').disabled=false;$('#upload').value=''}}
$('#upload').onchange=e=>upload([...e.target.files]);const drop=$('.asset-panel');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');upload([...e.dataTransfer.files])};
document.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{if(!page())return;page()[el.dataset.field]=el.value;mark();drawCanvas();drawThumbs()}));
$('#size-options').onclick=e=>{const b=e.target.closest('[data-size]');if(b&&page()){page().size=b.dataset.size;mark();drawCanvas();drawInspector()}};
$('#crop-ratio').onchange=e=>{const p=page();p.cropRatio=e.target.value;p.ratio=p.cropRatio==='original'?p.originalRatio:Number(p.cropRatio);p.zoom=1;p.x=p.y=.5;mark();drawCanvas();drawInspector()};
for(const key of ['zoom','x','y'])$('#crop-'+key).oninput=e=>{page()[key]=Number(e.target.value);$('#crop-value').textContent=(page().zoom||1).toFixed(2)+'×';mark();drawCanvas()};
$('#reset-crop').onclick=()=>{const p=page();p.cropRatio='original';p.ratio=p.originalRatio;p.zoom=1;p.x=p.y=.5;mark();drawCanvas();drawInspector()};
function move(offset){const to=selected+offset;if(to<0||to>=book.pages.length)return;[book.pages[selected],book.pages[to]]=[book.pages[to],book.pages[selected]];selected=to;mark();select(selected)}$('#move-up').onclick=()=>move(-1);$('#move-down').onclick=()=>move(1);$('#duplicate').onclick=()=>{if(page())add({...page(),id:crypto.randomUUID()})};$('#delete-page').onclick=()=>{if(!page()||!confirm('删除这一页？素材库中的原图仍会保留。'))return;book.pages.splice(selected,1);selected=Math.min(selected,book.pages.length-1);mark();select(selected)};
let drag;const canvas=$('#page-canvas');canvas.onpointerdown=async e=>{const frame=e.target.closest('.photo-frame');if(!frame)return;e.preventDefault();const p=page(),img=await loadImage(book.assets.find(a=>a.id===p.assetId));const r=cropRect(img.naturalWidth,img.naturalHeight,p.ratio,p.zoom,p.x,p.y);drag={id:p.id,startX:e.clientX,startY:e.clientY,x:p.x,y:p.y,rx:(img.naturalWidth-r.sw)/r.sw,ry:(img.naturalHeight-r.sh)/r.sh,width:frame.clientWidth,height:frame.clientHeight};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag||page()?.id!==drag.id)return;const p=page();p.x=drag.rx?Math.max(0,Math.min(1,drag.x-(e.clientX-drag.startX)/(drag.width*drag.rx))):.5;p.y=drag.ry?Math.max(0,Math.min(1,drag.y-(e.clientY-drag.startY)/(drag.height*drag.ry))):.5;mark();drawCanvas();$('#crop-x').value=p.x;$('#crop-y').value=p.y};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
$('#publish').onclick=async()=>{if(importing){toast('请等待素材导入完成');return}const btn=$('#publish');btn.disabled=true;const snapshot=structuredClone(book);try{await save();const pages=[];for(let i=0;i<snapshot.pages.length;i++){btn.textContent=`生成中 ${i+1}/${snapshot.pages.length}`;const p=snapshot.pages[i];pages.push(p.type==='photo'?{...p,rendered:await renderPhoto(p,3200)}:p)}const result=await api('/api/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:book.title,pages})});toast(result.message)}catch(e){toast(e.message)}finally{btn.disabled=false;btn.textContent='生成发布版'}};
window.addEventListener('beforeunload',e=>{if(revision!==savedRevision){e.preventDefault();e.returnValue=''}});
try{book=await api('/api/draft');drawAssets();select(book.pages.length?0:-1);for(const p of book.pages){if(p.type==='photo'){try{previews.set(p.id,await renderPhoto(p,600))}catch{}}}drawThumbs()}catch(e){toast(e.message);$('#save-state').textContent='加载失败，请刷新'}
